### PR TITLE
Fix delete client

### LINKED ISSUE #119: BUG: Incorrect display message upon deleting client
Deleting client always displays client name as "Bob"

### PR DESCRIPTION
**Pull request by Print2PDF**
Delete client command should now display correct client information on success

Fixes #119 , #142 , #144 , #169

### CODE REVIEW

File: src/main/java/insurabook/storage/JsonAdaptedClient.java [hunk 1]
```diff
@@ -87,7 +87,7 @@ public Client toModelType(InsuraBook insuraBook) throws IllegalValueException {
 
         if (email == null) {
             throw new IllegalValueException(
-                    String.format(MISSING_FIELD_MESSAGE_FORMAT, InsuraDate.class.getSimpleName()));
+                    String.format(MISSING_FIELD_MESSAGE_FORMAT, Email.class.getSimpleName()));
         }
         if (!InsuraDate.isValidInsuraDate(email)) {
```
Comment (yong0112) [inline src/main/java/insurabook/storage/JsonAdaptedClient.java]: the checking of validity of the fields still using insuraDate which is inappropriate

**Review by yong0112 — APPROVED** [review]
LGTM
